### ISSUE TITLE
Console::setPositionCallback() does not correctly handle negative positions

### ISSUE THREAD

**Issue by digiexchris** [digiexchris/SurfaceGrinderAutomaton#1]
setposition x -10000 sets the target position to 10000

expected

the target should be set to -10000

**Comment by brunoroux** [comment]
this is probably already fixed and may have just been me confused by the console callback checking the position before the SM updated it

**Comment by digiexchris** [comment]
thanks @brunoroux I was thinking the same thing

**Comment by digiexchris** [comment]
Could not duplicate, closing
